server:
  port: 8080   # you can change if needed

spring:
  kafka:
    bootstrap-servers: localhost:9092   # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # allow deserializing custom classes

# custom property for your producer
general:
  kafka-topic: midas-transactions
